# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61eb0ae816edf4a8dc01bd69bf60c11e252e70f98a82d36e74a714026999ab1db34072e41121adb3854f5e2953edb6b492378f201346435e892a7a00996b394f

test:
  secret_key_base: 2caa91484b51a57c6117ef8074a96b6c88e94871ea1774c13c93c57d439df02d0cb9bcd93ca26606ada72841b8e2443c11ad2dce4ac811144f381abdade944fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
